apiVersion: apps/v1
kind: Deployment
metadata:
  name: tit-frontend
  labels:
    name: tit-frontend
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  strategy:
    type: RollingUpdate
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: tit-frontend
  template:
    metadata:
      labels:
        name: tit-frontend
    spec:
      containers:
      - name: tit-frontend
        image: {{ .Values.werf.image.titWebClient }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - secretRef:
            name: tit-frontend-secret
        startupProbe:
          periodSeconds: 5
          httpGet:
            scheme: HTTP
            port: 3000
            path: /
        livenessProbe:
          periodSeconds: 5
          httpGet:
            scheme: HTTP
            port: 3000
            path: /
