apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tit-frontend-redirect
  labels:
    name: tit-frontend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-tit-frontend-redirect@kubernetescrd
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tit-frontend
            port:
              number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tit-frontend
  labels:
    name: tit-frontend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: tit-frontend-letsencrypt
spec:
  tls:
  - secretName: tit-frontend-tls
    hosts:
    - {{ .Values.domain }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: tit-frontend
            port:
              number: 3000
