apiVersion: v1
kind: Secret
metadata:
  name: tit-frontend-secret
  labels:
    name: tit-frontend
type: Opaque
stringData:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
